services:
  mysql:
    image: mysql:8.0
    container_name: querydsl-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: querydsl
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
